spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "pgadmin"
    password: "pg1234!@"
#    hikari:
#      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  config: classpath:log4j2.yml